CREATE TABLE FAVORITE_PACKAGE
(
    CODE         VARCHAR2(30),
    LOYALTY_CODE VARCHAR2(50),
);

CREATE TABLE FAVORITE_ACTIVE_PACKAGE
(
    CONTRACT_ID  VARCHAR2(15),
    PACKAGE_CODE VARCHAR2(30),
    EXPIRED      DATE
);