--<editor-fold desc="DOCUMENT">
CREATE TABLE DOCUMENT (
  DOCUMENT_ID     RAW(16),
  DOCUMENT_NUMBER VARCHAR2(16),
  DOCUMENT_TYPE   VARCHAR2(32),
  CREATED         DATE DEFAULT sysdate,
  UPDATED         DATE DEFAULT sysdate
) TABLESPACE ANYWHERE;

ALTER TABLE DOCUMENT
  ADD CONSTRAINT DOCUMENT_ID_PK PRIMARY KEY (DOCUMENT_ID)
USING INDEX TABLESPACE ANYWHERE;

CREATE UNIQUE INDEX DOCUMENT_NUMBER_TYPE_IDX
  ON DOCUMENT (DOCUMENT_NUMBER, DOCUMENT_TYPE) TABLESPACE ANYWHERE;

ALTER TABLE DOCUMENT
MODIFY (DOCUMENT_NUMBER CONSTRAINT DOCUMENT_NUMBER_CON NOT NULL);
ALTER TABLE DOCUMENT
MODIFY (DOCUMENT_TYPE CONSTRAINT DOCUMENT_TYPE_CON NOT NULL);
ALTER TABLE DOCUMENT
MODIFY (CREATED CONSTRAINT DOCUMENT_CREATED_CON NOT NULL);
ALTER TABLE DOCUMENT
MODIFY (UPDATED CONSTRAINT DOCUMENT_UPDATED_CON NOT NULL);

GRANT SELECT, INSERT, UPDATE ON DOCUMENT TO &role_name.;
-- </editor-fold>

--<editor-fold desc="DOCUMENT_SUBSCRIPTION">
CREATE TABLE DOCUMENT_SUBSCRIPTION (
  CONSUMER_ID  NUMBER(19, 0),
  CABINET_CODE VARCHAR2(32),
  DOCUMENT_ID  RAW(16),
  DESCRIPTION  VARCHAR2(128),
  CREATED      DATE DEFAULT sysdate
) TABLESPACE ANYWHERE;

ALTER TABLE DOCUMENT_SUBSCRIPTION
  ADD CONSTRAINT DOCUMENT_SUBSCRIPTION_PK PRIMARY KEY (CONSUMER_ID, CABINET_CODE, DOCUMENT_ID)
USING INDEX TABLESPACE ANYWHERE;

ALTER TABLE DOCUMENT_SUBSCRIPTION
  ADD CONSTRAINT DOCUMENT_SUBSCRIPTION_ID_FK FOREIGN KEY (DOCUMENT_ID)
REFERENCES DOCUMENT (DOCUMENT_ID);

GRANT SELECT, INSERT, UPDATE, DELETE ON DOCUMENT_SUBSCRIPTION TO &role_name.;
-- </editor-fold>

--<editor-fold desc="PENALTY">
CREATE TABLE PENALTY (
  UIN                      VARCHAR2(32),
  PENALTY_DATE             DATE,
  STATUS                   VARCHAR2(16),
  TYPE                     VARCHAR(16),
  AMOUNT                   NUMBER(19, 0),
  DISCOUNT                 NUMBER(19, 0),
  DISCOUNT_EXPIRATION_DATE DATE,
  DOCUMENT_ID              RAW(16),
  VSTATUS GENERATED ALWAYS AS (
  DECODE("STATUS",
  'NEW', "STATUS",
  'EXPIRED', "STATUS")
  ) VIRTUAL
) TABLESPACE ANYWHERE;

ALTER TABLE PENALTY
  ADD CONSTRAINT PENALTY_UIN_PK PRIMARY KEY (UIN)
USING INDEX TABLESPACE ANYWHERE;

ALTER TABLE PENALTY
  ADD CONSTRAINT PENALTY_DOCUMENT_ID_FK FOREIGN KEY (DOCUMENT_ID)
REFERENCES DOCUMENT (DOCUMENT_ID);

ALTER TABLE PENALTY
MODIFY (PENALTY_DATE CONSTRAINT PENALTY_DATE_CON NOT NULL);
ALTER TABLE PENALTY
MODIFY (STATUS CONSTRAINT PENALTY_STATUS_CON NOT NULL);
ALTER TABLE PENALTY
MODIFY (TYPE CONSTRAINT PENALTY_TYPE_CON NOT NULL);
ALTER TABLE PENALTY
MODIFY (AMOUNT CONSTRAINT PENALTY_AMOUNT_CON NOT NULL);
ALTER TABLE PENALTY
MODIFY (DISCOUNT CONSTRAINT PENALTY_DISCOUNT_CON NOT NULL);
ALTER TABLE PENALTY
MODIFY (DOCUMENT_ID CONSTRAINT PENALTY_DOCUMENT_ID_CON NOT NULL);

CREATE INDEX PENALTY_DOCUMENT_ID_IDX
  ON PENALTY (DOCUMENT_ID) TABLESPACE ANYWHERE;

CREATE INDEX PENALTY_VSTATUS_IDX
  ON PENALTY (VSTATUS) TABLESPACE ANYWHERE;

GRANT SELECT, INSERT, UPDATE ON PENALTY TO &role_name.;
-- </editor-fold>
